####
## @file
## Jekyll configuration
##
## We try to push as much sitewide config as possible into this file, so a new deployment can start with just editing
## this file.
##
## If you need help with YAML syntax, here are some quick references for you:
## https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
## https://learnxinyminutes.com/docs/yaml/
##
## Throughout this file, you'll see two # marks at the start of a line for a permanent comment, and a single # for
## configuration options that can be enabled by removing the #.
##
## When adding new sections, be sure to name them so they make sense to others, and to document with good comments
## wherever possible/practical.
####

## Technical site info
#baseurl: "" # This is better empty
subpath: "/resume" # Could be a subsite of a domain at a path, ex. "/sub-site"
google_analytics: UA-697953-3 # The UA- code provided by GA
title: "Brad Czerniak"

####
## Resume
##
## All your resume information should be entered here rather than the HTML files or elsewhere.
##
## This section contains the same information as jsonresume.org schema, namespaced to site.resume and re-formatted by the
## Jekyll system to json.
resume:
  basics:
    name: "Brad Czerniak"
    label: "The solve-it-once guy"
    image: "https://bradczerniak.com/apple-touch-icon.png"
    summary: "Senior Drupal and JAMstack developer, dev team leader, entrepreneur, and librarian. Looking for challenges"
    website: "https://bradczerniak.com"
    email: "brad@solveitonce.com"
    phone: "(248) 721-0350"
    location:
      address: "1428 Mark Ave"
      postalCode: "MI 48146"
      city: "Lincoln Park"
      countryCode: "US"
      region: "Michigan"
    profiles:
      - network: "Facebook"
        username: "bradczerniak"
        url: "https://www.facebook.com/bradczerniak"
      - network: "Twitter"
        username: "ao5357"
        url: "https://twitter.com/ao5357"
      - network: "GitHub"
        username: "ao5357"
        url: "https://github.com/ao5357"
      - network: "drupal.org"
        username: "ao5357"
        url: "https://drupal.org/user/313975"
      - network: "LinkedIn"
        username: "bczerniak"
        url: "https://www.linkedin.com/in/bczerniak"
  work:
    - company: "Kingston Enterprises (Midas)"
      position: "Lubrication technician"
      website: "https://www.midas.com/detroit/store.aspx?shopnum=6754&dmanum=264"
      location:
        address: "2995 East Big Beaver Road"
        postalCode: "MI 48083"
        city: "Troy"
        countryCode: "US"
        region: "Michigan"
      startDate: "2000-05-01"
      endDate: "2000-10-31"
      summary: "Performed oil changes, assisted the mechanics with brakes, exhaust, and other repairs, and cleaned the shop."
      highlights:
        - "Reliably worked 56-hour weeks for the whole summer"
        - "Implemented a system for tracking brake shoe reclamation"
    - company: "Wayne State University Housing"
      position: "Network technician and Front desk attendant"
      website: "https://housing.wayne.edu/"
      location:
        address: "5221 Gullen Mall"
        postalCode: "MI 48202"
        city: "Detroit"
        countryCode: "US"
        region: "Michigan"
      startDate: "2004-08-01"
      endDate: "2005-05-31"
      summary: "Installed wireless routers and let people into the dormitory"
      highlights:
        - "Presented to Housing department heads to pitch becoming first IT RA"
    - company: "Barnes and Noble Booksellers"
      position: "Retail associate"
      website: "https://wayne.bncollege.com/shop/wayne/home"
      location:
        address: "82 West Warren"
        postalCode: "MI 48202"
        city: "Detroit"
        countryCode: "US"
        region: "Michigan"
      startDate: "2006-07-01"
      endDate: "2006-08-31"
      summary: "Helped stock satellite location for opening and worked the register"
      highlights:
        - "Learned to use point-of-sale machines"
    - company: "Southfield Public Library"
      position: "Adult Services Intern"
      website: "http://www.sfldlib.org/"
      location:
        address: "26300 Evergreen Road"
        postalCode: "MI 48076"
        city: "Southfield"
        countryCode: "US"
        region: "Michigan"
      startDate: "2007-02-12"
      endDate: "2008-05-08"
      summary: "Trainee librarian with special projects"
      highlights:
        - "Provided quality reference service in a diverse, fast-paced environment"
        - "Active in strategic planning process: assessment and evaluation"
        - "Improved year-over-year efficiency of paper tax form program"
    - company: "Canton Public Library"
      position: "Digital Resources Developer"
      website: "http://www.cantonpl.org/"
      location:
        address: "1200 S Canton Center Rd"
        postalCode: "MI 48188"
        city: "Canton"
        countryCode: "US"
        region: "Michigan"
      startDate: "2008-05-08"
      endDate: "2013-01-25"
      summary: "Technology librarian that did bleeding-edge stuff"
      highlights:
        - "Developed modules and themes for a Drupal-based website"
        - "Designed UI and incorporated branding for site and catalog"
        - "Launched a media and digitization lab"
        - "Hosted hacker/maker events and online programming"
        - "Presented at conferences about mobile devices and other technologies"
    - company: "Commercial Progression"
      position: "Senior Drupal Developer"
      website: "https://www.commercialprogression.com"
      location:
        address: "455 E Cady St #302"
        postalCode: "MI 48167"
        city: "Northville"
        countryCode: "US"
        region: "Michigan"
      startDate: "2013-02-04"
      endDate: "2018-08-14"
      summary: "Developed world-class Drupal websites for a wide variety of clients"
      highlights:
        - "Built sites, modules, and themes for Drupal-based client sites"
        - "Optimized continuous integration and developer workflow"
        - "Incubated brand-new lean Discovery and Architecture"
    - company: "Symmetri Marketing Group"
      position: "Director of Technology"
      website: "https://www.symmetrimarketing.com"
      location:
        address: "455 E Cady St #302"
        postalCode: "MI 48167"
        city: "Northville"
        countryCode: "US"
        region: "Michigan"
      startDate: "2018-08-14"
      endDate: "2020-02-14"
      summary: "Led a talented team of Drupal developers"
      highlights:
        - "Nurtured and supervised a team of developers"
        - "Executed a vision for reusable, component-based Drupal archtecture"
        - "Balanced administrative duties with development and site support"
        - "Liaison to sales, client service, and project management teams"
    - company: "Solve it once"
      position: "Proprietor"
      website: "https://solveitonce.com"
      location:
        address: "1428 Mark Ave"
        postalCode: "MI 48146"
        city: "Lincoln Park"
        countryCode: "US"
        region: "Michigan"
      startDate: "2020-04-20"
      summary: "Started the greatest tech company this world has ever seen"
      highlights:
        - "Impress clientele with prompt, high-quality Drupal and JAMstack work"
        - "Provide fast, low-waste branding, UX, and other services"
        - "Contribute open source solutions to the community"
  volunteer:
    - organization: "Canton Historical Society"
      position: "Board member (secretary, treasurer)"
      website: "http://www.cantonhistoricalsociety.org/"
      startDate: "2011-12-01"
      endDate: "2014-12-31"
      summary: "Served the people of Canton in preserving and teaching the township's history"
      highlights:
        - "Created two iterations of the society's website"
        - "Helped coordinate and execute the Brews, Brats, and Bands at the Barn annual fundraiser"
        - "Kept minutes and ledgers fastidiously as secretary and treasurer"
        - "Was a real stickler for parliamentary procedure"
    - organization: "Lower Barriers"
      position: "Founding member"
      website: "https://lowerbarriers.org"
      startDate: "2020-06-03"
      summary: "Open source software nonprofit for improving civic engagement"
      highlights:
        - "Filed articles of incorporation and other paperwork"
        - "Created code repositories that make it easier to run for office"
  education:
    - institution: "Troy Athens High School"
      location:
        address: "4333 John R Rd"
        postalCode: "MI 48085"
        city: "Troy"
        countryCode: "US"
        region: "Michigan"
      area: "General studies"
      studyType: "High School Diploma"
      startDate: "1999-09-01"
      endDate: "2003-06-15"
      gpa: "3.85"
      courses:
        - "Auto mechanics"
        - "Computer science 1"
        - "AP Chemistry"
        - "AP American History"
        - "AP World History"
        - "AP Economics"
        - "AP Calculus AB"
    - institution: "Wayne State University"
      location:
        address: "5221 Gullen Mall"
        postalCode: "MI 48202"
        city: "Detroit"
        countryCode: "US"
        region: "Michigan"
      area: "Economics"
      studyType: "Bachelor of Arts"
      startDate: "2003-09-01"
      endDate: "2006-12-31"
      gpa: "3.38"
      courses:
        - "Labor economics"
        - "Labor history"
        - "German"
        - "Spanish"
        - "Film history"
        - "American culture"
    - institution: "Wayne State University"
      location:
        address: "5221 Gullen Mall"
        postalCode: "MI 48202"
        city: "Detroit"
        countryCode: "US"
        region: "Michigan"
      area: "Library and Information Science"
      studyType: "Master"
      startDate: "2006-09-01"
      endDate: "2008-04-29"
      gpa: "3.91"
      courses:
        - "Multiculturalism"
        - "Web design"
        - "Digital libraries"
        - "Scripting languages"
        - "Competitive intelligence and data mining"
        - "Advanced reference"
        - "Advanced searching"
  awards:
    - title: "Best Crew"
      date: "2003-05-14"
      awarder: "Athens High School Theatre Department"
      summary: "Stage Managed 2 out of 3 productions my senior year and basically lived in the auditorium"
  publications:
    - name: "Library Websites Adapt to Smartphone Growth"
      publisher: "Library Journal"
      releaseDate: "2012-07-26"
      website: "http://www.thedigitalshift.com/2012/07/mobile/library-websites-adapt-to-smartphone-growth/"
      summary: "Prescient predictions of responsive design in libraries"
  skills:
    - name: "HTML"
      level: "Expert"
      keywords: ["Hypertext Markup Language", "HTML5"]
    - name: "Drupal"
      level: "Expert"
      keywords: ["Drupal 8", "Drupal 9", "Views", "Paragraphs", "modules and themes"]
    - name: "JavaScript"
      level: "Expert"
      keywords: ["JS", "jQuery", "nodejs", "vanilla JS", "npm", "ES6"]
    - name: "CSS"
      level: "Expert"
      keywords: ["Cascading Stylesheets", "CSS3"]
    - name: "Accessibility"
      level: "Expert"
      keywords: ["a11y", "WAI ARIA", "WCAG AAA", "Section 508"]
    - name: "git"
      level: "Expert"
      keywords: ["GitHub", "Version control"]
    - name: "PHP"
      level: "Expert"
      keywords: ["PHP Hypertext Preprocessor", "PHP 7"]
    - name: "MySQL"
      level: "Expert"
      keywords: ["MariaDB", "Queries", "Relational databases", "PDO"]
    - name: "Responsive web design"
      level: "Expert"
      keywords: ["RWD", "Mobile first", "Media queries", "components", "style guides"]
    - name: "Progressive enhancement"
      level: "Expert"
      keywords: ["Graceful degradation", "usability"]
  languages:
    - language: "English"
      fluency: "Native speaker"
    - language: "German"
      fluency: "Basic vocabulary"
    - language: "Spanish"
      fluency: "Basic vocabulary"
    - language: "Hebrew"
      fluency: "Alphabetical"
  interests:
    - name: "Jogging"
    - name: "Ultimate Frisbee"
#  references:
#    - name: ""
#      reference: ""

## The <html> tag has language and language direction. We can make it configurable
html:
  dir: "ltr"
  lang: "en"
  locale: "en_US" # Technically used for open_graph, but we can set it here

## Standard <meta> tags for SEO, etc.
meta:
  description: "Brad Czerniak is a web business problem-solver."
  generator: "[Jekyll](https://github.com/mojombo/jekyll)"
  image:
    alt: "Site default social image" # It's okay for this to be an empty string if the image is decorative
    src: required/meta-image--default.jpg
  robots: "index,follow"

## Open Graph - the parts not inferred from other site/meta info above
## @see https://ogp.me/
open_graph:
  og_type: website
#  fb_app_id: "XXXXXXXXXX"

## schema.org
## @see https://schema.org/docs/schemas.html
schema:
  type: "CreativeWork" # (default for site, often "CreativeWork")
  publisher:
    type: "Person" # Whether a "Person" or "Organization" is the publisher of the site.

## Twitter cards
## @see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
twitter:
  card: "summary_large_image"
  creator: "@ao5357"
  site: "@ao5357"

## Woff2 files declared as webfonts in your css, relative to /assets/fonts/
## Placing them here sets them to be preloaded in the head, which reduces request chaining for better performance.
## @see https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content
woff:
  - "public_sans/public_sans_variable.woff2"
  - "public_sans/public_sans_variable_italic.woff2"

## Content license (comment out to disable entirely)
## @see https://creativecommons.org/share-your-work/
content_license:
  name: "CC BY-SA 4.0"
  url: "http://creativecommons.org/licenses/by-sa/4.0/"

## Jekyll configs
## @see https://jekyllrb.com/docs/configuration/
collections_dir: collections
encoding: utf-8
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - netlify.toml
  - readme.md
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
future: true
highlighter: rouge
include:
  - ".htaccess"
keep_files:
  - ".git"
  - ".svn"
kramdown:
  auto_ids: true
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: false
  input: GFM
  parse_block_html: false
  parse_span_html: false
  show_warnings: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: [1, 2, 3, 4, 5, 6]
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: false
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
paginate: 30
paginate_path: /blog/page-:num/
permalink: /blog/:title/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
profile: true
safe: true
sass:
  sass_dir: assets/css
  style: :compressed
strict_front_matter: true
theme: jekyll-theme-primer
timezone: Etc/UTC # Allows use to set dates/times without a GMT offset.
unpublished: false
whitelist:
  - jekyll-redirect-from
